import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  root: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: '300px',
    background: 'linear-gradient(180deg, #eef2ff 0%, #f6f6f9 180px, #f6f6f9 100%)',
    zIndex: 999,
    overflowY: 'auto',
    padding: '28px 32px 48px',
    fontFamily:
      '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    color: '#212134',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: '-0.02em',
    color: '#0f172a',
  },
  subtitle: {
    margin: '6px 0 0',
    color: '#64748b',
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 520,
  },
  headerActions: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  viewTabs: {
    display: 'flex',
    gap: 6,
    marginBottom: 16,
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 12,
    padding: 6,
    width: 'fit-content',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
  },
  viewTab: {
    border: '1px solid transparent',
    background: 'transparent',
    color: '#475569',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  },
  viewTabActive: {
    background: '#4f46e5',
    borderColor: '#4f46e5',
    color: '#fff',
  },
  ghostBtn: {
    border: '1px solid #c7d2fe',
    background: '#fff',
    color: '#3730a3',
    borderRadius: 8,
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  },
  ghostBtnActive: {
    background: '#312e81',
    borderColor: '#312e81',
    color: '#fff',
  },
  linkBtn: {
    border: 'none',
    background: 'transparent',
    color: '#4f46e5',
    cursor: 'pointer',
    fontSize: 12,
    padding: 0,
    fontWeight: 600,
  },
  toolbar: {
    display: 'flex',
    gap: '10px',
    alignItems: 'stretch',
    marginBottom: '20px',
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 12,
    padding: 10,
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
  },
  search: {
    flex: 1,
    minWidth: 200,
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    outline: 'none',
    background: '#f8fafc',
  },
  select: {
    minWidth: 140,
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: '10px 12px',
    fontSize: 13,
    outline: 'none',
    background: '#f8fafc',
    color: '#334155',
    fontWeight: 600,
  },
  primaryBtn: {
    background: '#4f46e5',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '10px 18px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: 'nowrap',
  },
  errorBanner: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#b91c1c',
    borderRadius: 10,
    padding: '10px 14px',
    marginBottom: 16,
    fontSize: 13,
    fontWeight: 500,
  },
  allEventsPanel: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 14,
    padding: '12px 8px 16px',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
  },
  card: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
    transition: 'box-shadow 0.15s ease, border-color 0.15s ease',
  },
  cardOpen: {
    borderColor: '#c7d2fe',
    boxShadow: '0 8px 24px rgba(79, 70, 229, 0.08)',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    padding: '16px 18px',
    cursor: 'pointer',
  },
  chevron: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: '#eef2ff',
    color: '#4338ca',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 700,
    flexShrink: 0,
    marginRight: 10,
  },
  leadTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: '#0f172a',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  leadIdPill: {
    fontSize: 12,
    fontWeight: 700,
    color: '#4338ca',
    background: '#eef2ff',
    borderRadius: 999,
    padding: '2px 8px',
  },
  metaRow: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 6,
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px 14px',
    alignItems: 'center',
  },
  metaStat: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
  },
  severityPill: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 999,
    padding: '2px 8px',
    textTransform: 'uppercase' as const,
  },
  badges: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  badge: {
    fontSize: 11,
    padding: '3px 9px',
    borderRadius: 999,
    background: '#eef2ff',
    color: '#3730a3',
    fontWeight: 600,
    border: '1px solid #e0e7ff',
  },
  tabs: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    padding: '12px 18px',
    borderTop: '1px solid #f1f5f9',
    background: '#f8fafc',
  },
  tab: {
    border: '1px solid #e2e8f0',
    background: '#fff',
    borderRadius: 999,
    padding: '6px 12px',
    fontSize: 12,
    cursor: 'pointer',
    color: '#475569',
    fontWeight: 600,
  },
  tabActive: {
    background: '#4f46e5',
    borderColor: '#4f46e5',
    color: '#fff',
  },
  eventList: {
    padding: '8px 18px 18px',
    maxHeight: 460,
    overflowY: 'auto',
    background: 'linear-gradient(90deg, #eef2ff 0 2px, transparent 2px)',
    marginLeft: 26,
  },
  eventRow: {
    position: 'relative',
    padding: '12px 14px 12px 18px',
    marginBottom: 8,
    background: '#fff',
    border: '1px solid #eef2ff',
    borderRadius: 10,
    boxShadow: '0 1px 1px rgba(15, 23, 42, 0.03)',
  },
  eventDot: {
    position: 'absolute',
    left: -21,
    top: 18,
    width: 10,
    height: 10,
    borderRadius: '50%',
    background: '#818cf8',
    border: '2px solid #fff',
    boxShadow: '0 0 0 1px #c7d2fe',
  },
  eventMeta: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  eventTime: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: 500,
  },
  eventAction: {
    fontSize: 13,
    fontWeight: 700,
    color: '#1e293b',
  },
  eventDesc: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 1.45,
  },
  empty: {
    padding: '48px 16px',
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 14,
  },
  emptyCard: {
    background: '#fff',
    border: '1px dashed #cbd5e1',
    borderRadius: 14,
    padding: '48px 24px',
    textAlign: 'center',
    color: '#64748b',
  },
};
