/** Error codes for business-loan-scoring-criteria */

export const BlScoreErr = {
  VALIDATION: 'BL_SCORE_ERR_VALIDATION',
  BUREAU_SUMMARY_MISSING: 'BL_SCORE_ERR_BUREAU_SUMMARY_MISSING',
  MISSING_WEIGHT_ROW: 'BL_SCORE_ERR_MISSING_WEIGHT_ROW',
  INVALID_RULES_SHAPE: 'BL_SCORE_ERR_INVALID_RULES_SHAPE',
  LENDER_NOT_FOUND: 'BL_SCORE_ERR_LENDER_NOT_FOUND',
  INTERNAL: 'BL_SCORE_ERR_INTERNAL',
  MISSING_MIN_CIBIL: 'BL_SCORE_ERR_MISSING_MIN_CIBIL',
  DIV_BY_ZERO: 'BL_SCORE_ERR_DIV_BY_ZERO',
  MISSING_FOIR: 'BL_SCORE_ERR_MISSING_FOIR',
  MISSING_MAX_DPD_DAYS_ALLOWED: 'BL_SCORE_ERR_MISSING_MAX_DPD_DAYS_ALLOWED',
  MISSING_CC_LIMIT: 'BL_SCORE_ERR_MISSING_CC_LIMIT',
  MISSING_ACTIVE_UNSECURED: 'BL_SCORE_ERR_MISSING_ACTIVE_UNSECURED',
  MISSING_ENQUIRIES_3M: 'BL_SCORE_ERR_MISSING_ENQUIRIES_3M',
  MISSING_MIN_ANNUAL_TURNOVER: 'BL_SCORE_ERR_MISSING_MIN_ANNUAL_TURNOVER',
  MISSING_MIN_VINTAGE_YEARS: 'BL_SCORE_ERR_MISSING_MIN_VINTAGE_YEARS',
  MISSING_MIN_INTEREST_RATE: 'BL_SCORE_ERR_MISSING_MIN_INTEREST_RATE',
  MISSING_LOAN_AMOUNT: 'BL_SCORE_ERR_MISSING_LOAN_AMOUNT',
  MISSING_MAX_LOAN_AMOUNT: 'BL_SCORE_ERR_MISSING_MAX_LOAN_AMOUNT',
  BELOW_DISPLAY_THRESHOLD: 'BL_SCORE_BELOW_DISPLAY_THRESHOLD',
  CRITERION_INACTIVE: 'BL_SCORE_CRITERION_INACTIVE',
  BLOCKED: 'BL_SCORE_BLOCKED',
} as const;

export type BlScoreErrorCode = (typeof BlScoreErr)[keyof typeof BlScoreErr];

export class BlScoreError extends Error {
  code: BlScoreErrorCode;
  httpStatus: number;
  details?: Record<string, unknown>;

  constructor(
    code: BlScoreErrorCode,
    message: string,
    httpStatus = 400,
    details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'BlScoreError';
    this.code = code;
    this.httpStatus = httpStatus;
    this.details = details;
  }
}
