/** Activity log categories for domain / timeline filters. */
export type ActivityCategory =
  | 'LEAD_FORM'
  | 'LOAN_APPLICATION'
  | 'EMAIL'
  | 'STATUS_REMARKS'
  | 'BUREAU_EXTRACTION'
  | 'LENDER_ELIGIBILITY'
  | 'LENDER_SCORING'
  | 'USER_REGISTRATION'
  | 'SYSTEM';

export const ACTIVITY_CATEGORIES: ActivityCategory[] = [
  'LEAD_FORM',
  'LOAN_APPLICATION',
  'EMAIL',
  'STATUS_REMARKS',
  'BUREAU_EXTRACTION',
  'LENDER_ELIGIBILITY',
  'LENDER_SCORING',
  'USER_REGISTRATION',
  'SYSTEM',
];

const ACTION_CATEGORY_MAP: Record<string, ActivityCategory> = {
  LEAD_CREATED: 'LEAD_FORM',
  LEAD_SUBMISSION_SUCCESS: 'LEAD_FORM',
  LEAD_SUBMISSION_FAILURE: 'LEAD_FORM',

  LOAN_APP_SUBMITTED: 'LOAN_APPLICATION',
  LOAN_APP_SUBMIT_FAILED: 'LOAN_APPLICATION',
  LOAN_STATUS_CHANGED: 'LOAN_APPLICATION',
  LOAN_ASSIGNMENT_CHANGED: 'LOAN_APPLICATION',

  EMAIL_DISPATCHED: 'EMAIL',
  EMAIL_FAILED: 'EMAIL',
  EMAIL_SKIPPED: 'EMAIL',

  LEAD_STATUS_CHANGED: 'STATUS_REMARKS',
  LEAD_REMARK_ADDED: 'STATUS_REMARKS',

  BUREAU_EXTRACT_STARTED: 'BUREAU_EXTRACTION',
  BUREAU_EXTRACT_COMPLETED: 'BUREAU_EXTRACTION',
  BUREAU_EXTRACT_FAILED: 'BUREAU_EXTRACTION',

  PL_ELIGIBILITY_RUN_START: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_BLOCKED: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_RULE: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_RULE_SKIP: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_LENDER: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_RUN_COMPLETE: 'LENDER_ELIGIBILITY',
  PL_ELIGIBILITY_CONNECTION_FAILED: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_RUN_START: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_BLOCKED: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_RULE: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_RULE_SKIP: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_LENDER: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_RUN_COMPLETE: 'LENDER_ELIGIBILITY',
  BL_ELIGIBILITY_CONNECTION_FAILED: 'LENDER_ELIGIBILITY',
  AI_MATCH_GENERATED: 'LENDER_ELIGIBILITY',

  PL_SCORE_RUN_START: 'LENDER_SCORING',
  PL_SCORE_CRITERION: 'LENDER_SCORING',
  PL_SCORE_CRITERION_SKIP: 'LENDER_SCORING',
  PL_SCORE_CRITERION_INACTIVE: 'LENDER_SCORING',
  PL_SCORE_LENDER: 'LENDER_SCORING',
  PL_SCORE_RANK_COMPLETE: 'LENDER_SCORING',
  PL_SCORE_RUN_DONE: 'LENDER_SCORING',
  PL_SCORE_BLOCKED: 'LENDER_SCORING',
  BL_SCORE_RUN_START: 'LENDER_SCORING',
  BL_SCORE_CRITERION: 'LENDER_SCORING',
  BL_SCORE_CRITERION_SKIP: 'LENDER_SCORING',
  BL_SCORE_CRITERION_INACTIVE: 'LENDER_SCORING',
  BL_SCORE_LENDER: 'LENDER_SCORING',
  BL_SCORE_RANK_COMPLETE: 'LENDER_SCORING',
  BL_SCORE_RUN_DONE: 'LENDER_SCORING',
  BL_SCORE_BLOCKED: 'LENDER_SCORING',

  ADVISOR_LOGIN_SUCCESS: 'USER_REGISTRATION',
  ADVISOR_LOGIN_FAILURE: 'USER_REGISTRATION',
  ADVISOR_REGISTRATION_SUCCESS: 'USER_REGISTRATION',
  ADVISOR_REGISTRATION_FAILURE: 'USER_REGISTRATION',
  ADVISOR_APPROVED: 'USER_REGISTRATION',
  ADMIN_USER_CREATED: 'USER_REGISTRATION',
  LOGIN_SUCCESS: 'USER_REGISTRATION',
  LOGIN_FAILURE: 'USER_REGISTRATION',

  MAINTENANCE_TOGGLED: 'SYSTEM',
  LOGS_PURGED: 'SYSTEM',
  LOG_CLEANUP_CRON: 'SYSTEM',
};

export function categoryFromAction(action: string): ActivityCategory {
  return ACTION_CATEGORY_MAP[action] ?? 'SYSTEM';
}

export function isValidCategory(value: unknown): value is ActivityCategory {
  return typeof value === 'string' && ACTIVITY_CATEGORIES.includes(value as ActivityCategory);
}
