/** Error codes for personal-loan-scoring-criteria */

export const PlScoreErr = {
  VALIDATION: 'PL_SCORE_ERR_VALIDATION',
  BUREAU_SUMMARY_MISSING: 'PL_SCORE_ERR_BUREAU_SUMMARY_MISSING',
  MISSING_WEIGHT_ROW: 'PL_SCORE_ERR_MISSING_WEIGHT_ROW',
  INVALID_RULES_SHAPE: 'PL_SCORE_ERR_INVALID_RULES_SHAPE',
  LENDER_NOT_FOUND: 'PL_SCORE_ERR_LENDER_NOT_FOUND',
  INTERNAL: 'PL_SCORE_ERR_INTERNAL',
  MISSING_MIN_CIBIL: 'PL_SCORE_ERR_MISSING_MIN_CIBIL',
  DIV_BY_ZERO: 'PL_SCORE_ERR_DIV_BY_ZERO',
  MISSING_FOIR: 'PL_SCORE_ERR_MISSING_FOIR',
  MISSING_MAX_DPD_DAYS_ALLOWED: 'PL_SCORE_ERR_MISSING_MAX_DPD_DAYS_ALLOWED',
  MISSING_CC_LIMIT: 'PL_SCORE_ERR_MISSING_CC_LIMIT',
  MISSING_ACTIVE_UNSECURED: 'PL_SCORE_ERR_MISSING_ACTIVE_UNSECURED',
  MISSING_ENQUIRIES_3M: 'PL_SCORE_ERR_MISSING_ENQUIRIES_3M',
  MISSING_MIN_MONTHLY_INCOME: 'PL_SCORE_ERR_MISSING_MIN_MONTHLY_INCOME',
  MISSING_MIN_EMPLOYMENT_MONTHS: 'PL_SCORE_ERR_MISSING_MIN_EMPLOYMENT_MONTHS',
  MISSING_MIN_INTEREST_RATE: 'PL_SCORE_ERR_MISSING_MIN_INTEREST_RATE',
  MISSING_LOAN_AMOUNT: 'PL_SCORE_ERR_MISSING_LOAN_AMOUNT',
  MISSING_MAX_LOAN_AMOUNT: 'PL_SCORE_ERR_MISSING_MAX_LOAN_AMOUNT',
  BELOW_DISPLAY_THRESHOLD: 'PL_SCORE_BELOW_DISPLAY_THRESHOLD',
  CRITERION_INACTIVE: 'PL_SCORE_CRITERION_INACTIVE',
  BLOCKED: 'PL_SCORE_BLOCKED',
} as const;

export type PlScoreErrorCode = (typeof PlScoreErr)[keyof typeof PlScoreErr];

export class PlScoreError extends Error {
  code: PlScoreErrorCode;
  httpStatus: number;
  details?: Record<string, unknown>;

  constructor(
    code: PlScoreErrorCode,
    message: string,
    httpStatus = 400,
    details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'PlScoreError';
    this.code = code;
    this.httpStatus = httpStatus;
    this.details = details;
  }
}
